permissions:
  contents: write

on:
  push: {}

jobs:
  build-debug:
    uses: ./.github/workflows/build.yml
    with:
      debug: 1
      build_type: debug
  build-snapshot:
    if: github.branch == 'master'
    uses: ./.github/workflows/build.yml
    with:
      debug: 0
      build_type: snapshot
